Repository CosmWasm/docs, pull requests merged in 2024-11, with the labels that each got.

#169 PART 1 Introduction to `counter` smart contract
  src/pages/cw-multi-test/getting-started/counter.mdx
  src/pages/cw-multi-test/getting-started/counter/_meta.json
  src/pages/cw-multi-test/getting-started/counter/counter-cosmwasm.mdx
  src/pages/cw-multi-test/getting-started/counter/counter-sylvia.mdx
  src/pages/cw-multi-test/getting-started/writing-tests.mdx
Labels: multitest

#170 PART 2 `counter` smart contract in CosmWasm
  src/pages/cw-multi-test/getting-started/counter/counter-cosmwasm.mdx
Labels: multitest

#171 PART 3 `counter` smart contract in Sylvia
  src/pages/cw-multi-test/getting-started/counter/counter-sylvia.mdx
Labels: multitest

#172 PART 4 Introduction to writing tests
  src/pages/cw-multi-test/getting-started/writing-tests.mdx
  src/pages/cw-multi-test/getting-started/writing-tests/_meta.json
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-cosmwasm.mdx
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-sylvia.mdx
Labels: multitest

#173 PART 5 Writing tests for CosmWasm contract
  src/pages/cw-multi-test/getting-started/_meta.json
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-cosmwasm.mdx
Labels: multitest

#184 Fixed broken link
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-cosmwasm.mdx
Labels: bug

#186 Testing contract written in Sylvia
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-sylvia.mdx
Labels: multitest

#187 Fixes to chapter `Writing tests/CosmWasm`
  src/pages/cw-multi-test/getting-started/writing-tests/writing-tests-cosmwasm.mdx
Labels: multitest

#190 Documented operations on blocks
  src/pages/cw-multi-test/blocks.mdx
  src/pages/cw-multi-test/features.mdx
Labels: multitest

#134 Document `Item`
  src/pages/storey/containers.mdx
  src/pages/storey/containers/item.mdx
Labels: storey
